# Catálogo de señas de Manos que Hablan
SENAS = [
    ("hola","👋","Mano abierta saludando."),
    ("adiós","👋","Movimiento de despedida con la mano."),
    ("gracias","🙏","Gesto de agradecimiento."),
    ("por favor","🤲","Gesto amable para pedir algo."),
    ("perdón","🙇","Gesto para pedir disculpas."),
    ("sí","👍","Pulgar hacia arriba."),
    ("no","👎","Pulgar hacia abajo."),
    ("bien","😊","Expresa que algo está bien."),
    ("mal","😞","Expresa que algo está mal."),
    ("ayuda","🆘","Señal para pedir ayuda."),
    ("yo","🙋","Señala a la propia persona."),
    ("tú","👉","Señala a otra persona."),
    ("mamá","👩","Seña relacionada con mamá."),
    ("papá","👨","Seña relacionada con papá."),
    ("bebé","👶","Seña relacionada con un bebé."),
    ("amigo","🫂","Expresa amistad."),
    ("maestro","🧑‍🏫","Persona que enseña."),
    ("comer","🍴","Gesto relacionado con comer."),
    ("beber","🥤","Gesto relacionado con beber."),
    ("dormir","😴","Gesto relacionado con dormir."),
    ("jugar","🎮","Actividad de jugar."),
    ("correr","🏃","Actividad de correr."),
    ("leer","📖","Actividad de leer."),
    ("escribir","✍️","Actividad de escribir."),
    ("caminar","🚶","Actividad de caminar."),
    ("ver","👀","Gesto relacionado con mirar o ver."),
    ("querer","❤️","Expresa querer o cariño."),
    ("casa","🏠","Lugar donde vivimos."),
    ("escuela","🏫","Lugar donde aprendemos."),
    ("libro","📚","Objeto para leer."),
    ("agua","💧","Bebida esencial."),
    ("pan","🍞","Alimento."),
    ("leche","🥛","Bebida."),
    ("pelota","⚽","Objeto usado para jugar."),
    ("carro","🚗","Medio de transporte."),
    ("sol","☀️","Estrella que vemos de día."),
    ("luna","🌙","Astro que vemos de noche."),
    ("perro","🐶","Animal doméstico."),
    ("gato","🐱","Animal doméstico."),
    ("pájaro","🐦","Animal que vuela."),
    ("pez","🐟","Animal que vive en el agua."),
    ("feliz","😄","Expresa alegría."),
    ("triste","😢","Expresa tristeza."),
    ("enojado","😠","Expresa enojo."),
    ("miedo","😨","Expresa temor."),
    ("amor","❤️","Expresa cariño o amor."),
    ("frío","🥶","Expresa sensación de frío."),
    ("calor","🥵","Expresa sensación de calor."),
    ("uno","1️⃣","Número uno."),
    ("dos","2️⃣","Número dos."),
    ("tres","3️⃣","Número tres."),
]

RANGOS = [
    (0, "🌱", "Semilla"),
    (50, "🐥", "Pollito"),
    (120, "🦋", "Mariposa"),
    (220, "🐬", "Delfín"),
    (350, "🦁", "León"),
    (520, "🦉", "Búho sabio"),
    (750, "🦅", "Águila"),
    (1000, "🏆", "Campeón"),
    (1500, "👑", "Maestro"),
]

FRASES = [
    ["yo", "quiero", "agua"],
    ["mamá", "quiero", "pan"],
    ["yo", "como", "pan"],
    ["amigo", "jugar", "pelota"],
    ["yo", "leo", "libro"],
    ["yo", "veo", "perro"],
    ["quiero", "leche"],
]
